"""Production MCP tool boundary for accepted MAX Grounding capabilities."""

from __future__ import annotations

from typing import Annotated, Any

from mcp.server import MCPServer
from pydantic import BaseModel, ConfigDict, Field

from .evidence_authority import (
    DEFAULT_REQUIRED_SOURCES,
    MAX_EVIDENCE_REFERENCE_CHARS,
    MAX_EVIDENCE_REFERENCES,
)
from .service import GroundingService
from .verification import (
    MAX_ANSWER_CLAIMS,
    MAX_CLAIM_KEY_CHARS,
    MAX_CLAIM_VALUE_CHARS,
)
from .wire import to_wire


class CandidateClaimProposal(BaseModel):
    """Bounded model proposal; canonical IDs are generated by MAX Grounding."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    claim_key: str = Field(
        min_length=1,
        max_length=MAX_CLAIM_KEY_CHARS,
        description=(
            "Structured fact key, or exact_evidence for a literal span from fetched evidence."
        ),
    )
    value: str = Field(
        min_length=1,
        max_length=MAX_CLAIM_VALUE_CHARS,
        description=(
            "Proposed fact value. For exact_evidence, supply verbatim source text; "
            "semantic paraphrases are not evidence."
        ),
    )
    claim_id: str | int | None = Field(
        default=None,
        description=(
            "Optional bookkeeping only. This value is ignored; MAX Grounding "
            "generates the canonical claim ID."
        ),
    )


EvidenceReferenceProposal = Annotated[
    str,
    Field(
        min_length=MAX_EVIDENCE_REFERENCE_CHARS,
        max_length=MAX_EVIDENCE_REFERENCE_CHARS,
        pattern=r"^[A-Za-z0-9_-]{43}$",
        description=(
            "Must be the opaque evidence_ref returned by this server's "
            "fetch_evidence tool. Never provide a source URL."
        ),
    ),
]
CandidateClaimProposals = Annotated[
    list[CandidateClaimProposal],
    Field(min_length=1, max_length=MAX_ANSWER_CLAIMS),
]
EvidenceReferenceProposals = Annotated[
    list[EvidenceReferenceProposal],
    Field(min_length=1, max_length=MAX_EVIDENCE_REFERENCES),
]


def mcp_search_web(
    service: GroundingService,
    *,
    query: str,
    language: str = "en",
    country: str | None = None,
    freshness: str | None = None,
    max_search_rounds: int = 2,
    results_per_call: int = 5,
    min_evidence_sources: int = 1,
) -> dict[str, Any]:
    return to_wire(
        service.search_web(
            query,
            language=language,
            country=country,
            freshness=freshness,
            max_search_rounds=max_search_rounds,
            results_per_call=results_per_call,
            min_evidence_sources=min_evidence_sources,
        )
    )


def mcp_fetch_evidence(
    service: GroundingService,
    *,
    url: str,
) -> dict[str, Any]:
    return to_wire(service.fetch_evidence(url))


def mcp_index_evidence(
    service: GroundingService,
    *,
    urls: tuple[str, ...] | list[str],
) -> dict[str, Any]:
    if not isinstance(urls, (tuple, list)):
        raise ValueError("urls must be a bounded list or tuple")
    return to_wire(service.index_evidence(tuple(urls)))


def mcp_query_evidence(
    service: GroundingService,
    *,
    query: str,
    limit: int = 5,
) -> list[dict[str, Any]]:
    return to_wire(service.query_evidence(query, limit=limit))


def mcp_verify_claims(
    service: GroundingService,
    *,
    claims: list[dict[str, Any]] | tuple[dict[str, Any], ...],
    evidence_refs: list[str] | tuple[str, ...],
    required_sources: int = DEFAULT_REQUIRED_SOURCES,
) -> dict[str, Any]:
    """Return only the server-built verified packet for bounded claim proposals."""
    return to_wire(
        service.verify_candidate_claims(
            claims,
            evidence_refs=evidence_refs,
            required_sources=required_sources,
        )
    )


def register_mcp_tools(server: MCPServer, service: GroundingService) -> None:
    """Register four retrieval tools and one server-verified output tool."""

    def _tool_search_web(
        query: str,
        language: str = "en",
        country: str | None = None,
        freshness: str | None = None,
        max_search_rounds: int = 2,
        results_per_call: int = 5,
        min_evidence_sources: int = 1,
    ) -> dict[str, Any]:
        """Search the configured web provider and return bounded source evidence."""
        return mcp_search_web(
            service,
            query=query,
            language=language,
            country=country,
            freshness=freshness,
            max_search_rounds=max_search_rounds,
            results_per_call=results_per_call,
            min_evidence_sources=min_evidence_sources,
        )

    def _tool_fetch_evidence(url: str) -> dict[str, Any]:
        """Securely fetch one public evidence URL and return extracted text provenance."""
        return mcp_fetch_evidence(service, url=url)

    def _tool_index_evidence(urls: list[str]) -> dict[str, Any]:
        """Securely fetch and persist a bounded list of evidence URLs."""
        return mcp_index_evidence(service, urls=urls)

    def _tool_query_evidence(query: str, limit: int = 5) -> list[dict[str, Any]]:
        """Query the accepted persistent semantic evidence index."""
        return mcp_query_evidence(service, query=query, limit=limit)


    def _tool_verify_claims(
        claims: CandidateClaimProposals,
        evidence_refs: EvidenceReferenceProposals,
        required_sources: int = DEFAULT_REQUIRED_SOURCES,
    ) -> dict[str, Any]:
        """Verify claims using opaque references returned by this server's fetch_evidence tool.

        claim_id is optional bookkeeping and ignored; canonical IDs are server-generated.
        evidence_refs must contain fetch_evidence evidence_ref values, never URLs.
        For general evidence statements use claim_key='exact_evidence' and provide a literal
        text span from fetched evidence; semantic paraphrases are not accepted as supported.
        """
        return mcp_verify_claims(
            service,
            claims=[claim.model_dump(exclude_none=True) for claim in claims],
            evidence_refs=evidence_refs,
            required_sources=required_sources,
        )

    server.tool(name="search_web", structured_output=True)(_tool_search_web)
    server.tool(name="fetch_evidence", structured_output=True)(_tool_fetch_evidence)
    server.tool(name="index_evidence", structured_output=True)(_tool_index_evidence)
    server.tool(name="query_evidence", structured_output=True)(_tool_query_evidence)
    server.tool(name="verify_claims", structured_output=True)(_tool_verify_claims)


def create_mcp_server(service: GroundingService) -> MCPServer:
    server = MCPServer(
        "MAX Grounding",
        instructions=(
            "Evidence retrieval and deterministic claim verification only. "
            "Tools return provenance-bearing evidence or a server-built verified packet; "
            "they do not generate free-form research conclusions. "
            "verify_claims requires opaque evidence_ref values returned by this server's "
            "fetch_evidence tool, never URLs; canonical claim IDs are server-generated. "
            "For generic exact evidence, use claim_key='exact_evidence' with a literal span "
            "from fetched text; semantic paraphrases are not marked supported."
        ),
    )
    register_mcp_tools(server, service)
    return server
