"""Shared deterministic helpers for Project Truth projections."""

from __future__ import annotations

from pathlib import Path
from typing import Any

def clean(value: Any) -> str:
    return str(value or "").strip()

def cell(value: Any) -> str:
    return clean(value).replace("|", "\\|").replace("\n", "<br>")

def bullets(values: list[Any], empty: str = "- None declared.") -> str:
    rows = [clean(x) for x in values if clean(x)]
    return "\n".join("- " + x for x in rows) if rows else empty

def normalize_markdown(text: str) -> str:
    """Apply safe deterministic Markdown normalization.

    This is formatting-only. It must not reorder semantic lists, lifecycle
    transitions, decision chronology, sequence edges, or evidence rows.
    """
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    out: list[str] = []
    in_fence = False
    previous_blank = False

    for raw in text.split("\n"):
        line = raw.rstrip()
        stripped = line.lstrip()
        if stripped.startswith("~~~") or stripped.startswith(chr(96) * 3):
            in_fence = not in_fence
            out.append(line)
            previous_blank = False
            continue

        if not in_fence and not line:
            if previous_blank:
                continue
            out.append("")
            previous_blank = True
            continue

        out.append(line)
        previous_blank = False

    while out and not out[-1]:
        out.pop()

    return "\n".join(out) + "\n"

def generated_header(digest: str, source_digest: str) -> str:
    # Keep the tracked header stable. Global input/source digests belong in the
    # compiler report; embedding them in every document would create needless
    # whole-pack churn after unrelated source edits.
    return "<!-- GENERATED BY PROJECT TRUTH COMPILER - DO NOT EDIT -->\n\n"

def claim_backlink_comment(specs: dict[str, dict], doc_name: str) -> str:
    claim_ids: list[str] = []
    for item in specs["claims.json"].get("claims", []):
        declared = {Path(clean(value)).name for value in item.get("documents", []) if clean(value)}
        claim_id = clean(item.get("id"))
        if claim_id and doc_name in declared:
            claim_ids.append(claim_id)
    if not claim_ids:
        return ""
    return "\n<!-- CLAIM_BACKLINKS: " + " ".join(sorted(set(claim_ids))) + " -->\n"

def auth_lookup(specs: dict[str, dict], concern: str) -> dict:
    for item in specs["authority.json"].get("authorities", []):
        if clean(item.get("concern")) == concern:
            return item
    return {}

def wanted_doc_names(
    required: set[str],
    contracts: dict[str, str],
    sequence: dict[str, bool],
) -> set[str]:
    wanted = set(required)
    wanted.update(
        {
            "SYSTEM_OVERVIEW.md",
            "PROJECT_MANIFEST.md",
            "CURRENT_STATE.md",
            "ROADMAP.md",
            "MODULE_MAP.md",
            "TEST_ACCEPTANCE_MATRIX.md",
            "DECISIONS.md",
            "KNOWN_DEFECTS.md",
            "GLOSSARY.md",
        }
    )
    if sequence.get("required", False):
        wanted.add("SEQUENCE_CONTRACTS.md")

    optional_map = {
        "api_contracts": "API_CONTRACTS.md",
        "data_contracts": "DATA_CONTRACTS.md",
        "ui_information_architecture": "UI_INFORMATION_ARCHITECTURE.md",
        "runbook": "RUNBOOK.md",
        "decisions": "DECISIONS.md",
        "known_defects": "KNOWN_DEFECTS.md",
        "glossary": "GLOSSARY.md",
        "changelog": "CHANGELOG.md",
    }
    for key, filename in optional_map.items():
        if contracts.get(key) != "not_applicable":
            wanted.add(filename)
    wanted.discard("PROJECT_PROFILE.yaml")
    return wanted
