#!/usr/bin/env python3
"""Representative LITE and STANDARD adoption fixtures for SW2-08."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

from project_profile import parse_profile, validate_profile


MARKER = "<!-- GENERATED BY PROJECT TRUTH COMPILER - DO NOT EDIT -->\n"


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def profile_text(profile: str, *, generated: bool, sequence: bool) -> str:
    return f"""schema_version: 1
profile: {profile}

contracts:
  api_contracts: optional
  data_contracts: optional
  ui_information_architecture: optional
  runbook: optional
  decisions: optional
  known_defects: optional
  glossary: optional
  changelog: optional

runtime:
  e2e_required: false

documentation:
  generated: {'true' if generated else 'false'}
  spec_root: .workflow
  docs_root: docs

sequence:
  required: {'true' if sequence else 'false'}
  runtime_trace_required: false

notes:
  profile_reason: sw2_08_{profile}_adoption_fixture
"""


def seed_specs(root: Path) -> None:
    write(
        root / ".workflow" / "roadmap.json",
        '{"schema_version":1,"current_phase":"ADOPTION","phases":[{"id":"ADOPTION","title":"Adoption fixture","status":"CURRENT","objective":"Validate profile adoption.","exit_criteria":["Structural handoff passes."]}]}\n',
    )
    write(
        root / ".workflow" / "state.json",
        '{"schema_version":1,"phase":"ADOPTION","status":"IN_PROGRESS","working_branch":"fixture","last_accepted_sha":"","last_accepted_branch":"","proven":[],"not_proven":[],"blockers":[],"next_authorized_actions":[],"blocked_actions":[]}\n',
    )


def doc(text: str, generated: bool) -> str:
    return (MARKER if generated else "") + text


def seed_docs(root: Path, profile: str, *, generated: bool, sequence: bool) -> None:
    docs = root / "docs"
    write(
        docs / "PROJECT_MANIFEST.md",
        doc(f"# Project Manifest\n\nGovernance profile: {profile}\n", generated),
    )
    write(
        docs / "SYSTEM_OVERVIEW.md",
        doc(
            "# System Overview\n\n"
            "Human comprehension status: PASS\n\n"
            "## One-minute summary\nFixture.\n\n"
            "## System at a glance\nFixture.\n\n"
            "## Major components\nFixture.\n\n"
            "## Main data flow\nFixture.\n\n"
            "## Main user workflows\nFixture.\n\n"
            "## Lifecycle and state\nFixture.\n\n"
            "## Authority model\nFixture.\n\n"
            "## Mutable vs immutable\nFixture.\n\n"
            "## Failure and recovery\nFixture.\n\n"
            "## Current project state\nFixture.\n\n"
            "## Proven vs not proven\nFixture.\n\n"
            "## Human comprehension gate\nPASS.\n",
            generated,
        ),
    )
    current = (
        "# Current State\n\n"
        "Authoritative SHA: fixture\n"
        "Status: IN_PROGRESS\n"
        "Roadmap phase: ADOPTION\n"
        "ROADMAP_SYNC: PASS\n"
        "Next authorized action: validate\n"
        f"Governance profile: {profile}\n"
    )
    if sequence:
        current += "Sequence policy: required\nCurrent sequence mode: DURING\nSEQUENCE_SYNC: PASS\n"
    write(docs / "CURRENT_STATE.md", doc(current, generated))
    write(
        docs / "ROADMAP.md",
        doc(
            "# Roadmap\n\nCurrent project phase: ADOPTION\n"
            "Current roadmap phase: ADOPTION\nROADMAP_SYNC: PASS\n",
            generated,
        ),
    )
    write(docs / "MODULE_MAP.md", doc("# Module Map\n\nFixture module.\n", generated))
    matrix = (
        "# Test Acceptance Matrix\n\nEvidence boundary: structural fixture.\n"
        "Final tested source: fixture\n"
    )
    if sequence:
        matrix += "\n## Sequence contract evidence\n\nSEQUENCE_SYNC: PASS\n"
    write(docs / "TEST_ACCEPTANCE_MATRIX.md", doc(matrix, generated))

    if profile != "standard":
        return

    write(
        docs / "SOURCE_AUTHORITY_MAP.md",
        doc("# Source Authority Map\n\nCanonical authority: fixture source.\n", generated),
    )
    write(docs / "ARCHITECTURE.md", doc("# Architecture\n\nFixture.\n", generated))
    write(
        docs / "WORKFLOW_STATE_MACHINE.md",
        doc("# Workflow State Machine\n\nFixture.\n", generated),
    )
    write(
        docs / "SYMBOL_INDEX.md",
        doc("# Symbol Index\n\nAuthority SHA: fixture\n\n| File | Symbol |\n|---|---|\n| app.py | main |\n", generated),
    )
    write(
        docs / "FLOW_INDEX.md",
        doc("# Flow Index\n\nAuthority SHA: fixture\n\n## Flow inventory\n\nFixture.\n", generated),
    )
    write(docs / "DOC_SYNC_MATRIX.md", doc("# Doc Sync Matrix\n\nFixture.\n", generated))
    write(
        docs / "SEQUENCE_CONTRACTS.md",
        doc(
            "# Sequence Contracts\n\n## Modes\nDURING.\n\n"
            "## Flow inventory\nFixture.\n\n## Mismatch handling\nFail closed.\n",
            generated,
        ),
    )
    write(docs / "sequence" / "sessions" / "ADOPTION.json", '{"session_id":"ADOPTION"}\n')


def run_fixture(skill_root: Path, profile: str, *, generated: bool, sequence: bool) -> None:
    with tempfile.TemporaryDirectory(prefix=f"skill-workflow-{profile}-adoption-") as td:
        root = Path(td)
        write(root / "PROJECT_PROFILE.yaml", profile_text(profile, generated=generated, sequence=sequence))
        seed_specs(root)
        seed_docs(root, profile, generated=generated, sequence=sequence)

        parsed = parse_profile(root / "PROJECT_PROFILE.yaml")
        failures = validate_profile(parsed)
        if failures:
            raise RuntimeError(f"{profile} profile invalid: {failures}")

        proc = subprocess.run(
            [sys.executable, str(skill_root / "scripts" / "validate_handoff.py"), "--root", str(root)],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        if proc.returncode != 0 or f"RESULT=PASS profile={profile}" not in proc.stdout:
            raise RuntimeError(f"{profile} adoption fixture failed\n{proc.stdout}")
        print(f"{profile.upper()}_ADOPTION_FIXTURE=PASS")


def main() -> int:
    skill_root = Path(__file__).resolve().parent.parent
    run_fixture(skill_root, "lite", generated=False, sequence=False)
    run_fixture(skill_root, "standard", generated=True, sequence=True)
    print("STRICT_ADOPTION_FIXTURE=PERMANENT_STRICT_E2E_LANE")
    print("ADOPTION_PROFILE_MATRIX=PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
